allowBuilds:
  electron-winstaller: false
  esbuild: true
overrides:
  'source-map-js@<1.2.2': 1.2.2
  'brace-expansion@<1.1.20': 1.1.20
  'brace-expansion@>=2.0.0 <2.1.6': 2.1.6
  'brace-expansion@>=5.0.0 <5.0.11': 5.0.11
patchedDependencies:
  http-cache-semantics@4.2.0: patches/http-cache-semantics@4.2.0.patch
minimumReleaseAgeExclude:
  - '@types/node@22.20.2'
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - zod@4.6.1
