import { copyFileSync, existsSync, mkdirSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { _electron as electron, expect, test } from "@playwright/test";
import type { AevorenBotApi } from "../../src/shared/contracts";
import { AppRepository } from "../../src/main/database";
import { WorkspaceService } from "../../src/main/workspace-service";
import { removeTestDirectory } from "./test-cleanup";
import { openBotList, openInspector } from "./navigation";

// UI/SQLite acceptance only. No model results are generated by this test; actual
// Provider and filesystem execution is covered by p0-real-scope.spec.ts.
test("chat, contacts and workspaces keep independent state and preserve data", async () => {
  test.setTimeout(120_000);
  const directory = mkdtempSync(join(tmpdir(), "aevoren-p0-navigation-"));
  const repository = new AppRepository(join(directory, "aevoren-bot.sqlite"));
  const firstRoot = join(directory, "资料库");
  const secondRoot = join(directory, "另一资料库");
  mkdirSync(firstRoot); mkdirSync(secondRoot);
  copyFileSync(join(process.cwd(), "LICENSE"), join(firstRoot, "LICENSE.md"));
  const service = new WorkspaceService(repository);
  const first = await service.registerRoot(firstRoot);
  const second = await service.registerRoot(secondRoot);
  const create = (name: string, projectId: string) => {
    const item = repository.createBot(projectId);
    return { ...item, bot: repository.updateBot(item.bot.id, item.bot.version, { name }) };
  };
  const researcher = create("研究助手", first.project.id);
  const editor = create("编辑助手", first.project.id);
  const reviewer = create("审阅助手", second.project.id);
  const room = repository.createRoom({ name: "资料工作群", projectId: first.project.id, memberBotIds: [researcher.bot.id, editor.bot.id] });
  repository.createMemory(researcher.bot.id, "本项目使用 Apache License 2.0。");
  repository.setSetting("appearance.theme", "dark", false);
  repository.close();
  const app = await electron.launch({ args: ["."], cwd: process.cwd(), env: {
    ...process.env, AEVOREN_BOT_USER_DATA_DIR: directory, AEVOREN_BOT_TEST_HIDDEN: "1", AEVOREN_BOT_DISABLE_UPDATES: "1",
  } });
  try {
    const page = await app.firstWindow();
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0]?.setSize(1440, 900));
    await expect(page.getByRole("tab", { name: "聊天", exact: true })).toHaveAttribute("aria-selected", "true");
    await expect(page.locator(".app-shell")).toHaveClass(/inspector-collapsed/u);
    await page.getByLabel("搜索聊天", { exact: true }).fill("研究助手");
    const row = page.locator(".bot-row").filter({ hasText: "研究助手" });
    await expect(row).toHaveCount(1);
    await row.click({ button: "right" });
    await page.getByRole("menuitem", { name: /移除聊天/u }).click();
    await expect(row).toHaveCount(0);

    await page.getByRole("tab", { name: "联系人", exact: true }).click();
    await page.locator(".bot-row").filter({ hasText: "研究助手" }).click();
    await expect(page.getByRole("region", { name: "联系人资料" })).toBeVisible();
    await page.getByRole("button", { name: "发消息", exact: true }).click();
    await expect(page.getByRole("heading", { name: "研究助手", exact: true })).toBeVisible();
    await expect(page.getByRole("tab", { name: "聊天", exact: true })).toHaveAttribute("aria-selected", "true");
    await page.getByLabel("搜索聊天", { exact: true }).fill("");
    await page.locator(".bot-row").filter({ hasText: "研究助手" }).click({ button: "right" });
    await page.getByRole("menuitem", { name: "清空聊天记录", exact: true }).click();
    const clear = page.getByRole("alertdialog", { name: "清空聊天记录？" });
    await expect(clear).toBeVisible();
    await clear.getByRole("button", { name: "清空记录", exact: true }).click();
    await expect(clear).toBeHidden();
    const retained = await page.evaluate(async (botId) => {
      const api = (window as unknown as { aevorenBot: AevorenBotApi }).aevorenBot;
      return { bots: await api.bots.list(), memory: await api.memories.list({ botId }), session: await api.sessions.getMain(botId) };
    }, researcher.bot.id);
    expect(retained.bots.ok && retained.bots.data.some(bot => bot.id === researcher.bot.id)).toBe(true);
    expect(retained.memory.ok && retained.memory.data.length).toBe(1);
    expect(retained.session.ok && retained.session.data.generation).toBe(researcher.session.generation + 1);
    expect(existsSync(join(firstRoot, "LICENSE.md"))).toBe(true);

    await page.getByRole("tab", { name: "联系人", exact: true }).click();
    await page.locator(".bot-row").filter({ hasText: "审阅助手" }).click();
    await page.getByLabel("选择已有群聊", { exact: true }).selectOption(room.room.id);
    await page.getByRole("button", { name: "加入群聊", exact: true }).click();
    await expect(page.getByRole("region", { name: "联系人资料" }).getByRole("status")).toContainText("已加入");
    const updated = await page.evaluate(async (roomId) => (window as unknown as { aevorenBot: AevorenBotApi }).aevorenBot.rooms.get(roomId), room.room.id);
    expect(updated.ok && updated.data.members.some(member => member.botId === reviewer.bot.id)).toBe(true);
    await page.getByRole("tab", { name: "工作区", exact: true }).click();
    await expect(page.getByRole("button", { name: "新建工作区", exact: true })).toBeVisible();
    await expect(page.locator(".sidebar-project").first()).toBeVisible();

    for (const width of [1180, 1020, 620, 390]) {
      await app.evaluate(({ BrowserWindow }, width) => BrowserWindow.getAllWindows()[0]?.setSize(width, 820), width);
      await openBotList(page);
      await page.getByRole("tab", { name: "聊天", exact: true }).click();
      await expect(page.getByLabel("搜索聊天", { exact: true })).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({ path: join(tmpdir(), `aevoren-p0-navigation-${width}.png`) });
      await page.getByRole("tab", { name: "联系人", exact: true }).click();
      await page.locator(".bot-row").filter({ hasText: "研究助手" }).click();
      await expect(page.getByRole("region", { name: "联系人资料" })).toBeVisible();
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({ path: join(tmpdir(), `aevoren-p0-contacts-${width}.png`) });
      await page.getByRole("button", { name: "发消息", exact: true }).click();
      await openInspector(page);
      const workspace = page.getByLabel("当前聊天工作区", { exact: true });
      await expect(workspace).toBeVisible();
      await expect(workspace).toHaveValue(first.project.id);
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
      await page.screenshot({ path: join(tmpdir(), `aevoren-p0-details-${width}.png`) });
      await page.getByRole("button", { name: "关闭 Bot 设置", exact: true }).click();
    }
    expect(errors).toEqual([]);
  } finally { await app.close(); removeTestDirectory(directory); }
});
