export const IPC = {
  botsList: "bots:list",
  botsCreate: "bots:create",
  botsUpdate: "bots:update",
  sessionsGetMain: "sessions:get-main",
  transcriptList: "transcript:list",
  messagesSend: "messages:send",
  messagesRetry: "messages:retry",
  messagesCancel: "messages:cancel",
  messagesGetStatus: "messages:get-status",
  runtimeGetSessionSnapshot: "runtime:get-session-snapshot",
  runtimeCancel: "runtime:cancel",
  runtimeRetry: "runtime:retry",
  settingsGetModel: "settings:get-model",
  settingsSaveModel: "settings:save-model",
  settingsTestModel: "settings:test-model",
  transcriptEvent: "events:transcript",
  sendStateEvent: "events:send-state",
  runtimeEvent: "events:runtime",
  appRendererReady: "app:renderer-ready",
  appBeforeClose: "app:before-close",
  appConfirmClose: "app:confirm-close",
  appCloseBlocked: "app:close-blocked",
} as const;
